on:
 push:
   branches:
   - main
   paths:
   - '01_infra/01_vpc/gcp/01_gcp_vpc/*'   #### 01_lambda == 01_vpc

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: 01_infra/01_vpc/gcp/01_gcp_vpc/  #### 01_lambda == 01_vpc

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       id: init
       run: |
         cp ../../../../02_tmp/01_vpc/gcp/* .
         cp ../../../../03_pro/gcp/02_provider.tf .
         
         echo "01_gcp.TF"
         cat 02_provider.tf
         echo "TFVARS"
         cat terraform.tfvars
     #    terraform init -backend-config="bucket=dunhuang-gansu-terraform-state"
       
     #- name: Terraform Plan
     #  run: terraform plan -lock=false

     #- name: Terraform Apply
     #  run: terraform apply -auto-approve -input=false -lock=false
