on:
 push:
   branches:
   - main
   paths:
   - '01_infra/01_lambda/lambda03/02_provider.tf'   #### 01_lambda == 01_lambda

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: 01_infra/01_lambda/lambda03/  #### 01_lambda == 01_lambda

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       id: init
       run: |
         cp ../../../02_tmp/01_lambda/* .
         sed -i -e "s/RESOURCE/lambda03/g" main.tf
         echo "MAIN.TF"
         cat main.tf
         echo "TFVARS"
         cat terraform.tfvars
     #    terraform init -backend-config="bucket=dunhuang-gansu-terraform-state"
       
     #- name: Terraform Plan
     #  run: terraform plan -lock=false

     #- name: Terraform Apply
     #  run: terraform apply -auto-approve -input=false -lock=false
