on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/test'

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: 01_infra/02_vpc/vpc03/   ### 01_lambda == 02_vpc  

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       # id: init
       run: |
         cp ../../../02_tmp/02_vpc/* . 
         sed -i -e "s/RESOURCE/vpc03/g" main.tf
         
         cp ../../../04_provider/aws/01_provider.tf .
         sed -i -e "s/RESOURCE/vpc03/g" main.tf
         sed -i -e "s/BUCKET/02_vpc/g" 01_provider.tf

         echo "01_aws.TF"
         cat 01_provider.tf

         cd ../../..
         git clone https://github.com/maxxam123/platf04.git
         rm -rf platf04/.github/workflows/02_vpc-vpc03.yaml
         rm -rf platf04/01_infra/02_vpc/vpc03
         echo "LAST........................."
      # rm -rf platf04/.github/workflows/01_vpc03.yaml
     #    terraform init -backend-config="bucket=dunhuang-gansu-terraform-state"
       
     #- name: Terraform Plan
     #  run: terraform plan -lock=false

     #- name: Terraform Destroy
     #  run: terraform destroy -auto-approve -input=false -lock=false
     - name: Pushes to another repository
       uses: cpina/github-action-push-to-another-repository@main
       env:
         API_TOKEN_GITHUB: ${{ secrets.NEWPLAT }}
       with:
         source-directory: "platf04"
         destination-github-username: "maxxam123"
         destination-repository-name: "platf04"
         user-email: hennighausenmax@gmail.com
         target-branch: main

 # build:
 #   runs-on: ubuntu-latest
 #   needs: terraform
 #   steps:
 #     - uses: actions/checkout@v3
 #     - name: test
 #       run: |
 #         ls -la
 #         git clone https://github.com/maxxam123/platf04.git
 #         cd platf04/.github/workflows
 #         ls -la
 #         rm -rf vpc03.yaml
 #         cd ../../../
 #         cd platf04/01_infra/01_lambda
 #         ls -la
 #         rm -rf vpc03
 #         cd ../../..

 #     - name: Pushes to another repository
 #       uses: cpina/github-action-push-to-another-repository@main
 #       env:
 #         API_TOKEN_GITHUB: ${{ secrets.NEWPLAT }}
 #       with:
 #         source-directory: "platf04"
 #         destination-github-username: "maxxam123"
 #         destination-repository-name: "platf04"
 #         user-email: hennighausenmax@gmail.com
 #         target-branch: main
